services:
  pdfmaster:
    image: pdfmaster
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
version: '3'

services:
  pdfmaster:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:0
    volumes:
      - ./src:/app/src
    entrypoint: ["python", "-m", "src.main"]
